"""add apelido e foto usuario

Revision ID: 285f2e04196a
Revises: 5d1e167d1099
Create Date: 2026-03-19 20:58:17.739402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285f2e04196a'
down_revision = '5d1e167d1099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apelido', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('apelido')

    # ### end Alembic commands ###
