"""add ciclo de vida empresa

Revision ID: 38f5ca33d12a
Revises: 1f268e9fc294
Create Date: 2026-03-22 15:27:09.323370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f5ca33d12a'
down_revision = '1f268e9fc294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_cod_empresa'))

    op.drop_table('empresa')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_abertura', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_encerramento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('motivo_encerramento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ativa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('ativa')
        batch_op.drop_column('motivo_encerramento')
        batch_op.drop_column('data_encerramento')
        batch_op.drop_column('data_abertura')

    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cod_empresa', sa.VARCHAR(length=10), nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=150), nullable=True),
    sa.Column('cnpj', sa.VARCHAR(length=18), nullable=False),
    sa.Column('ie', sa.VARCHAR(length=30), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('endereco', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data_abertura', sa.DATETIME(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj', name=op.f('uq_empresa_cnpj')),
    sa.UniqueConstraint('razao_social', name=op.f('uq_empresa_razao_social'))
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_cod_empresa'), ['cod_empresa'], unique=1)

    # ### end Alembic commands ###
