"""add cod_empresa e perfil

Revision ID: 5d1e167d1099
Revises: add_objeto_social_email
Create Date: 2026-03-19 17:17:46.448255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1e167d1099'
down_revision = 'add_objeto_social_email'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_empresa_cnpj'), ['cnpj'])
        batch_op.create_unique_constraint(batch_op.f('uq_empresa_razao_social'), ['razao_social'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_empresa', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('perfil', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_email'), ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_usuarios_cod_empresa_empresa'), 'empresa', ['cod_empresa'], ['cod_empresa'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_usuarios_cod_empresa_empresa'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_usuarios_email'), type_='unique')
        batch_op.drop_column('perfil')
        batch_op.drop_column('cod_empresa')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_empresa_razao_social'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_empresa_cnpj'), type_='unique')

    # ### end Alembic commands ###
