"""adicionar empresa_id clientes fornecedores

Revision ID: add_empresa_id_clientes_fornecedores
Revises: 1f268e9fc294
Create Date: 2026-06-01 19:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_empresa_id_clientes_fornecedores'
down_revision = '1f268e9fc294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adicionar coluna empresa_id na tabela clientes
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_clientes_empresa_id', 'empresas', ['empresa_id'], ['id'])
        batch_op.create_index('ix_clientes_empresa_id', 'clientes', ['empresa_id'])
    
    # Adicionar coluna empresa_id na tabela fornecedores
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_fornecedores_empresa_id', 'empresas', ['empresa_id'], ['id'])
        batch_op.create_index('ix_fornecedores_empresa_id', 'fornecedores', ['empresa_id'])
    
    # Atribuir registros existentes à empresa STAMPFE (ID=2)
    op.execute("UPDATE clientes SET empresa_id = 2 WHERE empresa_id IS NULL")
    op.execute("UPDATE fornecedores SET empresa_id = 2 WHERE empresa_id IS NULL")
    
    # Tornar empresa_id NOT NULL após atribuir valores
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('empresa_id', nullable=False)
    
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.alter_column('empresa_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index('ix_clientes_empresa_id')
        batch_op.drop_constraint('fk_clientes_empresa_id', 'clientes', type_='foreignkey')
        batch_op.drop_column('empresa_id')
    
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index('ix_fornecedores_empresa_id')
        batch_op.drop_constraint('fk_fornecedores_empresa_id', 'fornecedores', type_='foreignkey')
        batch_op.drop_column('empresa_id')
    
    # ### end Alembic commands ###
