"""Recriando tabela de versoes completa

Revision ID: c612dc5e68ad
Revises: 78bb049c5bd9
Create Date: 2026-04-02 11:37:56.977575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c612dc5e68ad'
down_revision = '78bb049c5bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('arquivos', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('autor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_versoes')),
    sa.UniqueConstraint('numero', name=op.f('uq_versoes_numero'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versoes')
    # ### end Alembic commands ###
