"""add logo transportadoras

Revision ID: c714416a5fed
Revises: e63390d0d654
Create Date: 2026-06-17 12:31:38.492179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c714416a5fed'
down_revision = 'e63390d0d654'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    """Verifica se a tabela existe antes de tentar dropar (evita erro em bancos
    onde ela já foi removida manualmente ou por outra migration)."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _safe_drop_table(table_name):
    if _table_exists(table_name):
        op.drop_table(table_name)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _safe_drop_table('campanhas')
    _safe_drop_table('estilistas')
    _safe_drop_table('com_tabelas_precos')
    _safe_drop_table('revendedores')
    _safe_drop_table('sistema_formas_pagamento')
    _safe_drop_table('entregadores')
    _safe_drop_table('transportadoras_rotas')
    _safe_drop_table('sistema_categorias_fornecedor')
    _safe_drop_table('influenciadores')
    _safe_drop_table('cat_malhas')
    _safe_drop_table('com_tabelas_precos_itens')
    with op.batch_alter_table('automacoes', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('campanha', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    # Corrige DEFAULT malformado (aspas duplas) na coluna mensagem_sucesso antes do batch recreate
    bind = op.get_bind()
    if _table_exists('capturas'):
        cols = [c['name'] for c in sa.inspect(bind).get_columns('capturas')]
        if 'mensagem_sucesso' in cols:
            bind.execute(sa.text(
                "ALTER TABLE capturas RENAME COLUMN mensagem_sucesso TO mensagem_sucesso_old"
            ))
            bind.execute(sa.text(
                "ALTER TABLE capturas ADD COLUMN mensagem_sucesso VARCHAR(250) "
                "DEFAULT 'Obrigado! Entraremos em contato.'"
            ))
            bind.execute(sa.text(
                "UPDATE capturas SET mensagem_sucesso = mensagem_sucesso_old "
                "WHERE mensagem_sucesso_old IS NOT NULL"
            ))
            bind.execute(sa.text(
                "ALTER TABLE capturas DROP COLUMN mensagem_sucesso_old"
            ))

    with op.batch_alter_table('capturas', schema=None, recreate='always') as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_capturas_slug'), ['slug'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cargos', schema=None, recreate='always') as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_cargos_codigo'), ['codigo'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_acessorios', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_cat_acessorios_classificacao_id_cat_acessorios_classificacoes'), 'cat_acessorios_classificacoes', ['classificacao_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cat_acessorios_unidade_id_cat_unidades'), 'cat_unidades', ['unidade_id'], ['id'])
        batch_op.drop_column('largura_mm')
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('vinculo_grade')
        batch_op.drop_column('altura_mm')

    with op.batch_alter_table('cat_atributos', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_categorias', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_cores', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_depositos', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('sigla',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_cat_depositos_sigla'), type_='unique')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_embalagens', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_cat_embalagens_sku'), ['sku'])
        batch_op.create_foreign_key(batch_op.f('fk_cat_embalagens_classificacao_id_cat_embalagens_classificacoes'), 'cat_embalagens_classificacoes', ['classificacao_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cat_embalagens_unidade_id_cat_unidades'), 'cat_unidades', ['unidade_id'], ['id'])
        batch_op.drop_column('altura_cm')
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('profundidade_cm')
        batch_op.drop_column('largura_cm')

    with op.batch_alter_table('cat_etiquetas', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_insumos', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('preco_custo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_unique_constraint(batch_op.f('uq_cat_insumos_sku'), ['sku'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_marcas', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_materiaprima', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('preco_custo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_foreign_key(batch_op.f('fk_cat_materiaprima_tipo_id_cat_materiaprima_tipos'), 'cat_materiaprima_tipos', ['tipo_id'], ['id'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_modelos', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_produtos', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('referencia',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_cat_produtos_tipo_material_id_cat_materiaprima_tipos'), 'cat_materiaprima_tipos', ['tipo_material_id'], ['id'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_produtos_variacoes', schema=None) as batch_op:
        batch_op.alter_column('custo_producao',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('cat_servicos', schema=None, recreate='always') as batch_op:
       batch_op.alter_column('tipo_item',
           existing_type=sa.String(length=2),
           server_default=sa.text("'09'"))
       batch_op.drop_column('empresa_id')
     
    with op.batch_alter_table('cat_subcategorias', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_tamanhos', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('fator_consumo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cat_unidades', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_clientes_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('comercial_acordos', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_estilistas', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_formas_pagamento', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('condicao_pagamento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_influenciadores', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_ministerios', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_operadoras_financeiras', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_parceiros_criativos', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_parcerias', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_parcerias_ministeriais', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('anexo_contrato')

    with op.batch_alter_table('comercial_perfis_venda', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_redes_influencia', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_redes_revendas', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('comercial_revendedores', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('tipo_contrato')
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('limite')

    with op.batch_alter_table('comercial_tabelas_precos', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('conversoes', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text('("MATRIZ")'))
        batch_op.create_unique_constraint(batch_op.f('uq_empresas_cpf'), ['cpf'])
        batch_op.create_foreign_key(batch_op.f('fk_empresas_cargo_id_cargos'), 'cargos', ['cargo_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_empresas_departamento_id_setores'), 'setores', ['departamento_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_empresas_setor_id_setores'), 'setores', ['setor_id'], ['id'])

    with op.batch_alter_table('empresas_contatos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_empresas_contatos_departamento_id_setores'), 'setores', ['departamento_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_empresas_contatos_setor_id_setores'), 'setores', ['setor_id'], ['id'])

    with op.batch_alter_table('financeiro_lancamentos', schema=None) as batch_op:
        batch_op.alter_column('numero_documento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_financeiro_lancamentos_caixa_id_financeiro_caixas'), 'financeiro_caixas', ['caixa_id'], ['id'])

    with op.batch_alter_table('financeiro_movimentacoes_caixa', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_empresa_id'), ['empresa_id'], unique=False)
        batch_op.drop_column('foto')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.alter_column('rg_orgao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('pis_pasep',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('nome_mae',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('nome_pai',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('titulo_eleitor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('reservista',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('tipo_sanguineo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('alergias',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('email_pessoal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('email_corporativo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('tipo_contrato',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('nivel_hierarquico',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('unidade_negocio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('turno',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('regime_escala',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('banco',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('tipo_conta',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('foto',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('path_documentos',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_funcionarios_centro_custo_id_centros_custo'), 'centros_custo', ['centro_custo_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_funcionarios_gestor_id_funcionarios'), 'funcionarios', ['gestor_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('jornada_intervalo')
        batch_op.drop_column('jornada_saida')
        batch_op.drop_column('jornada_entrada')

    with op.batch_alter_table('investidores', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('leads', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('motoristas', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('op_compras_orcamentos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_op_compras_orcamentos_comprador_id_funcionarios'), 'funcionarios', ['comprador_id'], ['id'])

    with op.batch_alter_table('op_compras_pedidos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_op_compras_pedidos_comprador_id_funcionarios'), 'funcionarios', ['comprador_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_op_compras_pedidos_fornecedor_id_fornecedores'), 'fornecedores', ['fornecedor_id'], ['id'])
        batch_op.drop_column('condicao_pagamento')

    with op.batch_alter_table('op_producao_eventos', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('op_vendas_orcamentos', schema=None) as batch_op:
        batch_op.alter_column('tipo_venda',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("Produtos")'))
        batch_op.alter_column('hora_entrega',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               existing_nullable=True)
        batch_op.alter_column('valor_desconto',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('outros_custos',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_frete',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_liquido',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('forma_envio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('ent_cep',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('ent_logradouro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('ent_numero',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('ent_bairro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('ent_cidade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('ent_uf',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.alter_column('ent_complemento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_op_vendas_orcamentos_vendedor_id_funcionarios'), 'funcionarios', ['vendedor_id'], ['id'])
        batch_op.drop_column('end_numero')
        batch_op.drop_column('end_entrega')
        batch_op.drop_column('forma_entrega')
        batch_op.drop_column('end_cidade')
        batch_op.drop_column('end_uf')

    with op.batch_alter_table('op_vendas_pedidos', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo_venda',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text('("Produtos")'))
        batch_op.alter_column('forma_envio',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('ent_cep',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('ent_logradouro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('ent_numero',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('ent_bairro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('ent_cidade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('ent_uf',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)
        batch_op.alter_column('ent_complemento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('valor_desconto',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('outros_custos',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_frete',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_bruto',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_liquido',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_foreign_key(batch_op.f('fk_op_vendas_pedidos_cliente_id_clientes'), 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_op_vendas_pedidos_vendedor_id_funcionarios'), 'funcionarios', ['vendedor_id'], ['id'])

    with op.batch_alter_table('ope_movimentos_estoque', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('perfis', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('setores', schema=None, recreate='always') as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_setores_nome'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_setores_codigo'), ['codigo'])
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('sistema_licencas', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('sistema_parametros', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('sistema_status', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')
        batch_op.drop_column('dashboard_categoria')

    with op.batch_alter_table('socios', schema=None, recreate='always') as batch_op:
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('transportadoras', schema=None, recreate='always') as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=255), nullable=True))
        batch_op.alter_column('cnpj_cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_usuario'), ['usuario'])

    with op.batch_alter_table('versoes', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('sinopse',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_publicacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('empresa_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('data_publicacao',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('data_inicio',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('sinopse',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuarios_usuario'), type_='unique')
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('cnpj_cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('logo')

    with op.batch_alter_table('socios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('sistema_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_categoria', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('sistema_parametros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('sistema_licencas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('setores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_setores_codigo'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_setores_nome'), ['nome'])

    with op.batch_alter_table('perfis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('ope_movimentos_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('op_vendas_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_op_vendas_pedidos_vendedor_id_funcionarios'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_op_vendas_pedidos_cliente_id_clientes'), type_='foreignkey')
        batch_op.alter_column('total_liquido',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_bruto',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_frete',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('outros_custos',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('valor_desconto',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('ent_complemento',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_uf',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_cidade',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_bairro',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_numero',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_logradouro',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_cep',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('forma_envio',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_venda',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("Produtos")'))
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('op_vendas_orcamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_uf', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('end_cidade', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('forma_entrega', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('end_entrega', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('end_numero', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_op_vendas_orcamentos_vendedor_id_funcionarios'), type_='foreignkey')
        batch_op.alter_column('ent_complemento',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_uf',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_cidade',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_bairro',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_numero',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_logradouro',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ent_cep',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('forma_envio',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('total_liquido',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_frete',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('outros_custos',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('valor_desconto',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('hora_entrega',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_venda',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('("Produtos")'))

    with op.batch_alter_table('op_producao_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('op_compras_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condicao_pagamento', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_op_compras_pedidos_fornecedor_id_fornecedores'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_op_compras_pedidos_comprador_id_funcionarios'), type_='foreignkey')

    with op.batch_alter_table('op_compras_orcamentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_op_compras_orcamentos_comprador_id_funcionarios'), type_='foreignkey')

    with op.batch_alter_table('motoristas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('investidores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jornada_entrada', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('jornada_saida', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('jornada_intervalo', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_funcionarios_gestor_id_funcionarios'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_funcionarios_centro_custo_id_centros_custo'), type_='foreignkey')
        batch_op.alter_column('path_documentos',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('foto',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_conta',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('banco',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('regime_escala',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('turno',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('unidade_negocio',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nivel_hierarquico',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_contrato',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('email_corporativo',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email_pessoal',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('alergias',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('tipo_sanguineo',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('reservista',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('titulo_eleitor',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome_pai',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome_mae',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('pis_pasep',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rg_orgao',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_fornecedores_empresa_id'))
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('financeiro_movimentacoes_caixa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('financeiro_lancamentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_financeiro_lancamentos_caixa_id_financeiro_caixas'), type_='foreignkey')
        batch_op.alter_column('numero_documento',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('empresas_contatos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_empresas_contatos_setor_id_setores'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_empresas_contatos_departamento_id_setores'), type_='foreignkey')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_empresas_setor_id_setores'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_empresas_departamento_id_setores'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_empresas_cargo_id_cargos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_empresas_cpf'), type_='unique')
        batch_op.alter_column('unidade',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text('("MATRIZ")'))

    with op.batch_alter_table('conversoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_tabelas_precos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_revendedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tipo_contrato', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('rating',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('comercial_redes_revendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_redes_influencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_perfis_venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_parcerias_ministeriais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anexo_contrato', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_parcerias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_parceiros_criativos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_operadoras_financeiras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_ministerios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_influenciadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_formas_pagamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('condicao_pagamento',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('comercial_estilistas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('comercial_acordos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_empresa_id'))
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cat_unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_tamanhos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('fator_consumo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(1.0)'))

    with op.batch_alter_table('cat_subcategorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_produtos_variacoes', schema=None) as batch_op:
        batch_op.alter_column('custo_producao',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('cat_produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cat_produtos_tipo_material_id_cat_materiaprima_tipos'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('referencia',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('cat_modelos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_materiaprima', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cat_materiaprima_tipo_id_cat_materiaprima_tipos'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.alter_column('preco_custo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('cat_marcas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_insumos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_cat_insumos_sku'), type_='unique')
        batch_op.alter_column('preco_custo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('sku',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('cat_etiquetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_embalagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('largura_cm', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('profundidade_cm', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('altura_cm', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cat_embalagens_unidade_id_cat_unidades'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cat_embalagens_classificacao_id_cat_embalagens_classificacoes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_cat_embalagens_sku'), type_='unique')
        batch_op.alter_column('sku',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('cat_depositos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_cat_depositos_sigla'), ['sigla'])
        batch_op.alter_column('sigla',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('cat_cores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_atributos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cat_acessorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altura_mm', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.add_column(sa.Column('vinculo_grade', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('largura_mm', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_cat_acessorios_unidade_id_cat_unidades'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cat_acessorios_classificacao_id_cat_acessorios_classificacoes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_cargos_codigo'), type_='unique')

    with op.batch_alter_table('capturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_capturas_slug'), type_='unique')

    with op.batch_alter_table('campanha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('automacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'empresas', ['empresa_id'], ['id'])

    op.create_table('com_tabelas_precos_itens',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('tabela_id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('variacao_id', sa.INTEGER(), nullable=True),
    sa.Column('preco_fixo', sa.REAL(), nullable=True),
    sa.Column('ajuste_especifico', sa.REAL(), nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['cat_produtos.id'], ),
    sa.ForeignKeyConstraint(['tabela_id'], ['com_tabelas_precos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat_malhas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=5), nullable=False),
    sa.Column('ativa', sa.BOOLEAN(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cat_malhas'))
    )
    op.create_table('influenciadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('nicho', sa.VARCHAR(length=50), nullable=True),
    sa.Column('plataforma', sa.VARCHAR(length=50), nullable=True),
    sa.Column('seguidores', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status_contrato', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=100), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('foto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_influenciadores'))
    )
    op.create_table('sistema_categorias_fornecedor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sistema_categorias_fornecedor'))
    )
    op.create_table('transportadoras_rotas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transportadora_id', sa.INTEGER(), nullable=False),
    sa.Column('uf', sa.VARCHAR(length=2), nullable=False),
    sa.Column('cidades', sa.TEXT(), nullable=True),
    sa.Column('modal', sa.VARCHAR(length=50), nullable=True),
    sa.Column('prazo_entrega', sa.INTEGER(), nullable=True),
    sa.Column('valor_base', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], name=op.f('fk_transportadoras_rotas_transportadora_id_transportadoras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transportadoras_rotas'))
    )
    op.create_table('entregadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tipo_veiculo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('placa', sa.VARCHAR(length=10), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entregadores'))
    )
    op.create_table('sistema_formas_pagamento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sistema_formas_pagamento'))
    )
    op.create_table('revendedores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('cnpj_cpf', sa.VARCHAR(length=20), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_revenda', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('end_cep', sa.VARCHAR(length=9), nullable=True),
    sa.Column('end_logradouro', sa.VARCHAR(length=150), nullable=True),
    sa.Column('end_numero', sa.VARCHAR(length=20), nullable=True),
    sa.Column('end_complemento', sa.VARCHAR(length=100), nullable=True),
    sa.Column('end_bairro', sa.VARCHAR(length=80), nullable=True),
    sa.Column('end_cidade', sa.VARCHAR(length=80), nullable=True),
    sa.Column('end_uf', sa.VARCHAR(length=2), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('foto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revendedores')),
    sa.UniqueConstraint('cnpj_cpf', name=op.f('uq_revendedores_cnpj_cpf'))
    )
    op.create_table('com_tabelas_precos',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('base_calculo', sa.TEXT(), server_default=sa.text("'venda_base'"), nullable=True),
    sa.Column('ajuste_tipo', sa.TEXT(), server_default=sa.text("'porcentagem'"), nullable=True),
    sa.Column('ajuste_valor', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=True),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('perfil_cliente', sa.TEXT(), server_default=sa.text("'todos'"), nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estilistas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('especialidade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('portfolio', sa.VARCHAR(length=255), nullable=True),
    sa.Column('disponibilidade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('foto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estilistas'))
    )
    op.create_table('campanhas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_campanha', sa.VARCHAR(length=150), nullable=False),
    sa.Column('identificador_webhook', sa.VARCHAR(length=150), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('vendedor_id', sa.INTEGER(), nullable=True),
    sa.Column('investimento_estimado', sa.NUMERIC(precision=16, scale=2), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('valor_diario', sa.NUMERIC(precision=16, scale=2), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('data_final', sa.DATE(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['comercial_vendedores.id'], name=op.f('fk_campanhas_vendedor_id_comercial_vendedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campanhas')),
    sa.UniqueConstraint('identificador_webhook', name=op.f('uq_campanhas_identificador_webhook'))
    )
    # ### end Alembic commands ###